server:
  port: 1026

spring:
  cloud:
    gateway:
      routes:
        - id: hcp-auth
          uri: lb://hcp-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: hcp-system
          uri: lb://hcp-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: hcp-operator
          uri: lb://hcp-operator
          predicates:
            - Path=/operator/**
          filters:
            - StripPrefix=1
        - id: hcp-gen
          uri: lb://hcp-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
    sentinel:
      enabled: false
    loadbalancer:
      nacos:
        enabled: true

security:
  ignore:
    whites:
      - /auth/login
      - /auth/register
